apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  connection_string: mongodb://NewTestUser:mUsoXEndrRS1vhfs@ac-gbftojw-shard-00-00.xxovbfs.mongodb.net:27017,ac-gbftojw-shard-00-01.xxovbfs.mongodb.net:27017,ac-gbftojw-shard-00-02.xxovbfs.mongodb.net:27017/?ssl=true&replicaSet=atlas-sciz7c-shard-0&authSource=admin&retryWrites=true&w=majority
